sudo: required
services:
  - docker

before_install:
  - docker build -t mack031892/docker-demo-app -f Dockerfile.dev .

script:
  - docker run mack031892/docker-demo-app npm run test

deploy:
  provider: heroku
  api_key: $API_KEY
  app: docker-demo-app-frontend
  on:
    branch: main
